// Code generated by goctl. DO NOT EDIT.
// Source: transform_url.proto

package server

import (
	"context"

	"shorturl/rpc/transform_url/internal/logic"
	"shorturl/rpc/transform_url/internal/svc"
	"shorturl/rpc/transform_url/transform_url"
)

type TransformUrlServer struct {
	svcCtx *svc.ServiceContext
	transform_url.UnimplementedTransformUrlServer
}

func NewTransformUrlServer(svcCtx *svc.ServiceContext) *TransformUrlServer {
	return &TransformUrlServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformUrlServer) Shorten(ctx context.Context, in *transform_url.ShortenReq) (*transform_url.ShortenResp, error) {
	l := logic.NewShortenLogic(ctx, s.svcCtx)
	return l.Shorten(in)
}

func (s *TransformUrlServer) Expand(ctx context.Context, in *transform_url.ExpandReq) (*transform_url.ExpandResp, error) {
	l := logic.NewExpandLogic(ctx, s.svcCtx)
	return l.Expand(in)
}
